### PR TITLE
Fix for issue #81 - sourceMappingUrl is wrong.

### PR DESCRIPTION
**Pull request by lewie9021**
Small change discussed in issue #81. Making the change indeed fixes source mapping so I thought I'd create this pull request.

### CODE REVIEW

**Comment by jorrit** [comment]
Maybe you can add a comment to the line to explain why it is necessary, for future reference.

**Comment by jhnns** [comment]
I see, we need to omit the source maps because otherwise webpack's source map comment would be ignored. Without `.omitSourceMapUrl` it looks like this:

```css
body {
  background: lightgrey; }

/*# sourceMappingURL=test/output/sass.map */  <-- from node-sass
/*# sourceMappingURL=data:application/json;base64,...*/  <-- from webpack
```

**Comment by jhnns** [comment]
Will be published soon. I just need to do some tests and I'll update the docs. Also related to #104.

**Comment by jhnns** [comment]
Shipped with `1.0.4`

**Pull request merged**
