### PR TITLE
Fix importing css files from sass/scss

### LINKED ISSUE #101: Cannot import CSS files
https://github.com/jtangelder/sass-loader/issues/91#issuecomment-103121653

### PR DESCRIPTION
**Pull request by jorrit**
Fixes #101

### CODE REVIEW

**Comment by jorrit** [comment]
I hope this fixes it.

**Comment by wmadden** [comment]
:+1: what's the ETA on this? It's been open for two weeks now?

**Comment by zallek** [comment]
I am using your fork in production, hope it will be merged soon :)

**Comment by jhnns** [comment]
That looks good, thx. :+1:

**Comment by jhnns** [comment]
Shipped with 1.0.3

**Pull request merged**
