### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by chicoxyzzy**
- node-sass v3.4.1 (including libsass [v3.3.1 with regression fixes](https://github.com/sass/libsass/releases/tag/3.3.1))
- update css-loader and style-loader to last versions

### CODE REVIEW

**Comment by browniefed** [comment]
This would be great to get in!

**Comment by ChrisCinelli** [comment]
Node-sass : 3.4.2 - Please and please merge and realese =)

**Comment by chicoxyzzy** [comment]
updated
- node-sass 3.4.2
- other deps
- test asserts

**Comment by ChrisCinelli** [comment]
@jhnns, what do you think? Can we close and release? 
We had a problem with syntax that is fixed in libsass v3.3.2 -> Node-sass  3.4.2

**Comment by jhnns** [comment]
Thx @chicoxyzzy. I'll merge it as soon as I've found some time.

@ChrisCinelli `node-sass` is a `peerDependency`. You should be able to bump the version in your project independently (as long as it is not a major version bump). That's why we've made it a `peerDependency`

**Comment by jhnns** [comment]
Shipped with `3.1.2`

**Pull request merged**
