### PR TITLE
Update node-sass (to work correctly with Node > 6.5.0)

### PR DESCRIPTION
**Pull request by chicoxyzzy**
Also update some other outdated deps.

Tested via `npm link` on couple of my projects

### CODE REVIEW

**Comment by chicoxyzzy** [comment]
@jtangelder @jhnns sorry for mentioning you guys directly but this stops everyone to upgrade to node > 6.5.x so it may be a crucial issue.

**Comment by jtangelder** [comment]
The caret (^) symbol already does this. https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004

**Comment by chicoxyzzy** [comment]
Yes but `npm install` won't update dependancies. So if you use nvm things will break.

**Comment by chicoxyzzy** [comment]
This is also an issue when you use Nexus, Artifactory, etc. because they will cache deps and when you run `npm i' cached old deps will be installed.

**Comment by jhnns** [comment]
Sorry, I don't understand this. Why can't people use node > 6.5 with the sass-loader? In fact, I'm using node 7.1.0 and everything is working fine (I've also tested it with node 6.9.0).

Besides that: Changing the `peerDependencies` is an unnecessary breaking change imho.

**Comment by chicoxyzzy** [comment]
Ok. we'll just clean Nexus' repo for now

**Pull request closed without merging**
