### PR TITLE
Add indentedSyntax to sass options of README

### PR DESCRIPTION
**Pull request by Kadrian**
This addresses #187

@jhnns Any objections? :grin:

### CODE REVIEW

**Comment by jhnns** [comment]
Yes :grin: 

That won't work, because the loader's `test` regex matches only scss-files. Why do you want to include that option in the README anyway? It's described in [node-sass's](https://github.com/sass/node-sass) readme.

**Comment by Kadrian** [comment]
@jhnns 1) You're right, updated.
2) The reason is that people usually start using webpack, They find out what loaders are, they figure out they need the sass-loader. Now if they want to configure to compile sass instead of scss, they naturally look at configuration options of the `sass-loader`. Then they don't find that option. They might even start wondering if sass-loader is actually capable of compiling sass and not only scss. #187 proves there are 6 other people who eventually found out about the option, and then actually took the time to search in the issues if there is something about the indentedSyntax. So I'm sure this is just a fraction of the people who are confused. So why make it any harder than it has to be?

**Comment by jhnns** [comment]
Ok, now I do understand you.

I used to have a small chapter about `.sass`-files, but then I read somewhere that it is deprecated (which is actually not true). I will re-add that small chapter.

However, I encourage you to learn more about node-sass and the underlying dependencies of all webpack loaders. Because loaders are often just connectors between webpack and another tool. So it's not sufficient to just understand the loader.

One thing, for instance, what people need to know is that node-sass is build on libsass, which is a C-port of the famous ruby library. It is *not* actually [Rubysass](http://sass-lang.com/). However, it tries to stick to it as close as possible.

**Comment by jhnns** [comment]
I think, #196 solves this "issue" as well

**Pull request closed without merging**
