### PR TITLE
Update webpack dependency to support 2.1.0-beta

### PR DESCRIPTION
**Pull request by RahavLussato**

### CODE REVIEW

**Comment by sompylasar** [comment]
@jtangelder Any plans to merge this?

**Comment by chrisdhanaraj** [comment]
pinging @jtangelder :)

**Comment by SEAPUNK** [comment]
You probably want to ping @jhnns instead, since he's the only active maintainer on this.

**Comment by jhnns** [comment]
Thx. Shipped with `3.2.1`

**Comment by sompylasar** [comment]
Yay!

**Pull request merged**
