### PR TITLE
Corrected invocations of raw-loader, style-loader and css-loader

### PR DESCRIPTION
**Pull request by clintonb**
Related: https://github.com/webpack/style-loader/issues/149

### CODE REVIEW

**Comment by clintonb** [comment]
@jhnns @jtangelder please review

**Comment by jhnns** [comment]
@clintonb cool thx.

Please also add `-loader` to `sass` and I will merge it. Webpack 2 removed this shorthand because it was a source of bugs for newcomers.

**Comment by clintonb** [comment]
@jhnns done

**Comment by jhnns** [comment]
Awesome

**Pull request merged**
