### PR TITLE
Introduce a queue such that a Node thread is available for fs tasks

### LINKED ISSUE #100: Silently fails/stalls webpack with no error
I have 2 imports that I use in multiple scss files that look like the following:

```
@import 'variables';
@import 'functions';
```

Everything works fine until I hit one file that has the exact same imports. Then, I see webpack build stall and it shows no errors. If I remove the import for this file, everything works, if I add it, it stalls. I don't understand why its happening because it's using the exact same imports. Problem still occurs if I remove everything in that file except for the imports. Problem does not occur if I remove the imports as well.

### PR DESCRIPTION
**Pull request by jorrit**
Should fix #100 and #119 but this needs testing.

### CODE REVIEW

**Comment by pthorn** [comment]
This seems to fix #100 for me.

**Comment by danielstefanovic** [comment]
I've tested it in the context of #100 and it works for me. :+1:

**Comment by lencioni** [comment]
I've also switched to this branch in the context of #100 and this seems to resolve the problem. :shipit:

**Comment by jhnns** [comment]
Nice! :+1:

Thx @jorrit

**Comment by dmitry** [comment]
Great! Solved. :+1:

**Pull request merged**
