### PR TITLE
Sass graph dependency to 1.0.3

### PR DESCRIPTION
**Pull request by justin808**

### CODE REVIEW

**Comment by akiran** [comment]
Thanks @justin808

**Comment by akiran** [comment]
@justin808,

I tested sass-loader with the fix
I got below error
```
 /home/kiran/node_modules/sass-loader/index.js:43
        callback(null, result.css, result.map);
        ^
TypeError: object is not a function
```
Are you seeing any errors in your project ?

**Comment by justin808** [comment]
@akiran Give me 10 min. Let me try.

**Comment by justin808** [comment]
I ran `npm i` after updating and then ran `node server.js`.

Worked just fine.

The below confirms that I got the new version. @akiran What is your test case that is failing?

You can see mine at https://github.com/justin808/react-webpack-rails-tutorial/.



```
npm i
-
> node-sass@2.0.0-beta install /Users/justin/j/react/react-webpack-rails-tutorial/node_modules/sass-loader/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /Users/justin/j/react/react-webpack-rails-tutorial/node_modules/sass-loader/node_modules/node-sass/vendor/darwin-x64/binding.node

> node-sass@2.0.0-beta postinstall /Users/justin/j/react/react-webpack-rails-tutorial/node_modules/sass-loader/node_modules/node-sass
> node scripts/build.js

sass-loader@0.4.0-beta.1 node_modules/sass-loader
├── sass-graph@1.0.3 (commander@2.6.0, lodash@2.4.1, glob@4.3.5)
└── node-sass@2.0.0-beta (get-stdin@3.0.2, object-assign@2.0.0, replace-ext@0.0.1, nan@1.6.1, shelljs@0.3.0, cross-spawn@0.2.3, chalk@0.5.1, mkdirp@0.5.0, meow@2.1.0, gaze@0.5.1, mocha@2.1.0, request@2.53.0)
```

**Comment by akiran** [comment]
I just update sass-loader in my project.

May be something wrong in my setup. I will test it and let you know

**Comment by akiran** [comment]
@justin808, I tested with your tutorial. Its workiing fine.

I errors I am getting is because of server-side rendering stuff in my project.
I thing we can make npm release with this.

@jhnns  What do you think ?

**Comment by jhnns** [comment]
Donnu ... if our tests are passing, we should publish it. If our tests are passing while we *know* that it doesn't work in actual projects, we should fix our tests :grin:

**Comment by jhnns** [comment]
You mean because of https://github.com/jtangelder/sass-loader/pull/41#issuecomment-70372228?

**Comment by akiran** [comment]
I think sass-loader is failing in my project because I am using webpack for server-side rendering in wrong way.  Otherwise its working fine.

Yes , Version number is marked beta. should be publish it ?

**Comment by jhnns** [comment]
Yep, I've published it.

We should consider using a major version bump and following semver...

**Pull request merged**
