### PR TITLE
Update node-sass

### PR DESCRIPTION
**Pull request by chicoxyzzy**

### CODE REVIEW

**Comment by jhnns** [comment]
Thx for the pull-request. Have you executed the tests after updating it?

I get 

```
Error: It's not clear which file to import for '@import "../node_modules/order/1/module"'.
Candidates:
  ../node_modules/order/1/_module.scss
  ../node_modules/order/1/_module.sass
  ../node_modules/order/1/_module.css
  ../node_modules/order/1/module.scss
  ../node_modules/order/1/module.sass
  ../node_modules/order/1/module.css
Please delete or rename all but one of these files.
```

which is a good thing, because it seems like they have finally decided to throw an error in these cases.

**Comment by chicoxyzzy** [comment]
Not sure if I should remove tests for `import-order-1` and rename others according to new index numbers or change tests somehow

**Comment by chicoxyzzy** [comment]
also should `extPrecedence` be removed from sources?

**Comment by chicoxyzzy** [comment]
updated:
- remove order tests
- fix understandable errors tests
- disable jshint noempty for empty block in case of css file

**Comment by jhnns** [comment]
Haha, that's exactly what I did yesterday evening :grinning:.

Anyway, thx. I'll pull in your commits. But now I need to remove the "funny resolving algorithm".

**Pull request merged**
