### PR TITLE
Use proper hook for SASS loader.

### PR DESCRIPTION
**Pull request by izaakschroeder**
This changes  a lot of stuff and the tests need to be updated to match. This builds a small project I have going right now but I haven't tested it majorly on anything else. Someone should look into it.

### CODE REVIEW

**Comment by izaakschroeder** [comment]
This is a good start on https://github.com/jtangelder/sass-loader/issues/31

**Comment by saki7** [comment]
:+1:

**Comment by jhnns** [comment]
Sorry for not answering this.

First of all: Thank you for work. I appreciate every contribution. Unfortunately this PR looks a bit over-complicated to me. Imho you're using too much internal stuff which can then break easily when @sokra changes something.

We can take the [less-loader](https://github.com/webpack/less-loader) as blueprint since it already has this feature for quite some time. The important code is [here](https://github.com/webpack/less-loader/blob/10279f468625bc31b62720f9da9847bebbcaab68/index.js#L86-L107). We can let webpack/enhanced-resolve do the resolving by calling

```javascript
// loaderContext is `this` inside the loader
loaderContext.resolve(context, moduleRequest, cb)
```

Take also a look at the [loader api](http://webpack.github.io/docs/loaders.html#resolve).

I'll publish a branch which contains the refactoring for node-sass@2.0.0

**Comment by izaakschroeder** [comment]
@jhnns A lot of this was indeed lifted from `less-loader`. However, one thing `less-loader` is missing (and this is not) is the ability to use module urls in imports.

```scss
@import "foo!/something";
```

The above is otherwise not possible. 

Also, `loaderContext.resolve` has its own set of problems which I struggled at before arriving at the current solution (in particular only one context is allowed and imports require more than one: root directory + "current directory" which is exposed really poorly in `node-sass`). The custom resolver is pretty much ripped from the webpack config loader.

If you don't want to merge this please close the branch and I'll maintain a fork myself, as I need the module loading capability.

**Comment by jhnns** [comment]
Oh, ok... didn't know that you already tried the `less-loader` approach.

@izaakschroeder what do you mean by "module urls"? Inlined loaders?
@sokra is that true? Does `loaderContext.resolve` not apply inline loaders?

I don't know what you mean by "root directory", but the described behavior should be done with [`loaderUtils.urlToRequest(url)`](https://github.com/webpack/loader-utils#urltorequest)

**Comment by izaakschroeder** [comment]
@jhnns the module loader allows you to do stupid things like `@import "css!less!foo";` where you can get a module to go through a precompile phase before being passed into `node-sass`. I use it for generating icon fonts, though I have not yet published the module. I could have sworn I tried every other approach, but they don't accept the `"foo!bar"` style.

How do you specify multiple paths to be searched? This approach allows you to feed the resolver multiple base paths and it will go through them in order, since SASS convention has no concept of `"./foo"` vs `"foo"` both have to be tried.

**Comment by jhnns** [comment]
Check out [this chapter](https://github.com/webpack/loader-utils#urltorequest) of loader-utils.

The `~`-prefix points to module directories. This should be consistent across all loaders where the import/require syntax doesn't differentiate between local and module directories. The css-loader and less-loader are already using it.

**Comment by jhnns** [comment]
I've implemented the custom importer with the less-loader approach.

Anyway, thanks for your suggestions :+1:

**Pull request closed without merging**
