### PR TITLE
Temporarily use require('node-sass').renderSync to avoid node-sass hang where the same file is imported by multiple other files

### PR DESCRIPTION
**Pull request by hedgepigdaniel**
This isn't a good long term solution but it fixes the problem and allows sass files to be compiled properly (if more slowly) by webpack until the bug in node-sass is fixed.

### CODE REVIEW

**Comment by hedgepigdaniel** [comment]
Fixes #100 #99

**Comment by matt-d-rat** [comment]
All be it a temporary solution, I definitely need this soon.

**Comment by patrickhaug** [comment]
How and where in webpack should I use renderSync?

**Comment by hedgepigdaniel** [comment]
If you'd like to try my fork with these fixes, you can do `npm install github.com:OpenLearningNet/sass-loader.git --save`. That means instead of using the main branch of sass-loader you use my branch which is the source of this pull request. Otherwise if this or another fix gets merged you can go back to jtangelder's branch.

**Comment by snario** [comment]
@hedgepigdaniel tried your solution but it only delays the hanging from 30% to 61% for me, so not a complete fix unfortunately

**Comment by jhnns** [comment]
Mhmmm ... do you know how deasync works? I'm a bit afraid to merge this when deasync is missing with node's event loop. It looks like black magic to me :grinning: 

Can more people try this PR locally? If it fixes the current issues (and deasync is "harmless"), I am willing to merge it.

**Comment by jhnns** [comment]
Issue fixed by #132.

But thank you for your effort and your proposal :+1:. Although I did not merge it, I do think that these contributions help to improve the code.

**Pull request closed without merging**
